BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: true
  label: active
  owner: sakurasep
  repo: Friends
  state: open
  type: volantis
HTTP_PROXY: false
LINK:
- link: https://blog.sakurasep.site/page/friends/
  theme: stellar
MAX_POSTS_NUM: 3
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - "\u4E5D\u6708\u7684\u751F\u6D3B"
    - https://hexo.sakurasep.site
    - https://cdn.sakurasep.site/Website/new_avatar_256.png
